remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "sunrise"

# Site Settings
title: "Antonios Mitsis"
name: "Antonios Mitsis"
description: "My personal blog and portfolio"
url: "https://anmitsis.github.io"
locale: "en-US"

# Author Settings
author:
  name: "Antonios Mitsis"
  avatar: "pfp.jpg"
  bio: "AI/ML Python Developer & Applied Mathematician"
  location: "Athens, Greece"
  links:
    - label: "Email: anmitsis@hotmail.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:anmitsis@hotmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/antonis-mitsis"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anmitsis"

# Defaults for Posts/Pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist

# Navigation
navigation:
  - title: "Posts"
    url: /year-archive/
  - title: "About"
    url: /about/

# Social Sharing 
social:
  type: Person
  name: "Antonios Mitsis"
  links:
    - https://github.com/anmitsis
    # Add LinkedIn 